### ISSUE TITLE
[QUESTION] How to turn warnings into errors?

### ISSUE THREAD

**Issue by cryptomilk** [csutils/cscppc#1]
It looks like it doesn't honor -Werror that warnings will be turned into errors and compilation stops.

See e.g.
https://gitlab.com/cryptomilk/libssh-mirror/-/jobs/101635647

**Comment by kdudka** [comment]
The static analyzer's exit code is intentionally ignored by csclng/cscppc to make sure that the build process continues natively even when the static analyzer's process times out, crashes, etc.

I do not think that using `-Werror` is an optimal solution to get notifications about potential bugs because it aborts the build prematurely.  When building in parallel, it may be even non-deterministic how many errors are reported before the build stops.

We usually use [cswrap](https://github.com/kdudka/cswrap) to capture all reports about potential bugs and [csdiff](https://github.com/kdudka/csdiff) to process them after a successful build.  This is exactly what csbuild does:

https://www.systutorials.com/docs/linux/man/1-csbuild/

Nevertheless, if you insist on using `-Werror`, it is not so difficult to implement (optional) propagation of the analyzer's exit code in csclng/cscppc.

**Comment by cryptomilk** [comment]
For CI (e.g. gitlab runner) I would like to have an error generated when someone introduces a bug. So it would be nice to tell it, fails hard if there is a warning or error. Also it would be nice to be able to ignore false positives :-)

**Comment by kdudka** [comment]
But that is exactly what csbuild is for (tested mainly with Travis CI so far).  You give it a build command, csbuild runs the build with static analyzers in the background and captures their output.  Once the build succeeds, it checks the captured output and returns non-zero exit code if a problem is detected.  You get all potential bugs reported in one run, which is not the case with `-Werror`.

As for false positives elimination, you can use differential scans to filter them out.  In that case, you go through the full list of potential bugs just once and then you are notified only when a **new** potential bug is introduced.  Travis CI provides the `$TRAVIS_COMMIT_RANGE` environment variable, which can be passed to the `--git-commit-range` option of csbuild.  I believe that your CI has something similar, doesn't it?

**Comment by cryptomilk** [comment]
In which format does GIT_COMMIT_RANGE need to be?

**Comment by cryptomilk** [comment]
Could you please extend the manpage by adding example like for the git commit range, I just guess that it is `<sha1>..<sha1>`.

For `--added-exit-code ADDED_EXIT_CODE` I guess the exit code is 0 by default? Could you add this to the manpage?

**Comment by kdudka** [comment]
Resolved via https://github.com/kdudka/csmock/pull/11
